using CffVaultManager.Domain.Enums;

namespace CffVaultManager.Domain.Entities;

/// <summary>
/// An immutable audit record. <see cref="TenantId"/> is null for platform-level
/// events generated by a SuperAdmin.
/// </summary>
public class AuditLogEntry
{
    private AuditLogEntry()
    {
        // Parameterless constructor for EF Core / serialization.
    }

    public AuditLogEntry(
        Guid id,
        Guid? tenantId,
        Guid userId,
        AuditAction action,
        Guid? vaultItemId = null,
        DateTimeOffset? timestamp = null,
        string? ipAddress = null,
        string? userAgent = null)
    {
        Id = Guard.AgainstEmptyGuid(id);
        TenantId = tenantId;
        UserId = Guard.AgainstEmptyGuid(userId);
        Action = action;
        VaultItemId = vaultItemId;
        Timestamp = timestamp ?? DateTimeOffset.UtcNow;
        IpAddress = ipAddress;
        UserAgent = userAgent;
    }

    public Guid Id { get; private set; }

    public Guid? TenantId { get; private set; }

    public Guid UserId { get; private set; }

    public User? User { get; set; }

    public Guid? VaultItemId { get; private set; }

    public VaultItem? VaultItem { get; set; }

    public AuditAction Action { get; private set; }

    public DateTimeOffset Timestamp { get; private set; }

    public string? IpAddress { get; private set; }

    public string? UserAgent { get; private set; }
}
