<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CffVaultManager.Domain\CffVaultManager.Domain.csproj" />
    <ProjectReference Include="..\CffVaultManager.Application\CffVaultManager.Application.csproj" />
    <ProjectReference Include="..\CffVaultManager.Crypto\CffVaultManager.Crypto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fido2" Version="4.0.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.2" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CffVaultManager.Infrastructure.Tests" />
  </ItemGroup>

</Project>
