namespace CffVaultManager.Domain.Enums;

public enum AuditAction
{
    Created,
    Viewed,
    Updated,
    Deleted,
    Shared,
    Revoked,
    Revealed,
    MfaEnabled,
    LoginSuccess,
    LoginFailed,
    AccountLocked,
    SessionsRevoked,
    MfaChallenge,
    EmailOtpRequested,
    EmailOtpVerified,
    EmailOtpFailed,
    TenantProvisioned,
    TenantSuspended,
    TenantReactivated,
    UserRoleChanged,
    PermanentlyDeleted,
    MasterPasswordChanged,
    MfaEmailOtpEnabled,
    MfaEmailOtpDisabled,
    WebAuthnCredentialRegistered,
    WebAuthnCredentialRemoved,
    ExternalShareLinkCreated,
    ExternalShareLinkRevoked,
}
